# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f493461a8c36e1fc399897839b54bfdada3d93fbca426fb9f816d846889a4c64821011c5825598d79743d51313faed02b08c77078ab5c2412513c7b4642d1665

test:
  secret_key_base: e9fb896524577bc06841357f42695eea8ad8a0b5bb6313d5ea9be0504cce685512e25b143fbf400f09f3797127b90e7f5b5b825bc71979f9bfe04f25150ae438

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
